### ISSUE TITLE
outputs of models on the GYAFC corpus

### ISSUE THREAD

**Issue by sunny371** [luofuli/DualRL#10]
I was wondering if you could release the outputs from both your DualRL model and your baselines for the **full test set** of the GYAFC corpus, for a better comparison of different models. Considering the privacy issues of the GYAFC dataset, could you show the outputs from different models and hide the inputs (for x->y, only show the y's)?

**Comment by luofuli** [comment]
The full outputs of GYAFC have been uploaded: [https://github.com/luofuli/DualRL/tree/master/outputs/GYAFC_Full](https://github.com/luofuli/DualRL/tree/master/outputs/GYAFC_Full)

Note that the results shown in our paper use the output in this dir: [https://github.com/luofuli/DualRL/tree/master/outputs/GYAFC](https://github.com/luofuli/DualRL/tree/master/outputs/GYAFC).

**Comment by sunny371** [comment]
Thank you very much!
Do you mean the results in your paper are evaluated using the subset of the test data of GYAFC corpus?

**Comment by luofuli** [comment]
Yes!

**Comment by sunny371** [comment]
Got it! Thanks a lot!
