### ISSUE TITLE
Why did you not use beam search for decoding?

### ISSUE THREAD

**Issue by jind11** [luofuli/DualRL#14]
I noticed that in your code, you used random and greedy mode for decoding, however, why did you not use beam search? It should be better than greedy decoding at least for evaluation, right? Thanks!

**Comment by luofuli** [comment]
Greedy decoding is good enough and can get the SOTA results. You can try beam search by just set the `decode_type` to `constants.BEAM ` at https://github.com/luofuli/DualRL/blob/2fae5bb41e62a2c1c8bd2d439baba01c9d8e4f21/dual_training.py#L109
