### ISSUE TITLE
关于bleu

### ISSUE THREAD

**Issue by nlpofwhat** [luofuli/DualRL#16]
请问一下那个bleu计算是所有样本的bleu得分的和，还是平均得分乘以100后得到的，不太懂，望大佬指教

**Comment by luofuli** [comment]
We use the [multi-blue.perl](https://github.com/luofuli/DualRL/blob/master/utils/script/multi-bleu.perl) script to compute the BLEU score. More can be founded at the script.

**Comment by nlpofwhat** [comment]
谢谢回复!------------------ 原始邮件 ------------------
发件人: "Fuli Luo"<notifications@github.com>
发送时间: 2019年11月19日(星期二) 下午4:57
收件人: "luofuli/DualRL"<DualRL@noreply.github.com>;
抄送: "learnby"<952167295@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [luofuli/DualRL] 关于bleu (#16)



We use the multi-blue.perl script to compute the BLEU score. More can be founded at the script.
 
&mdash;
