### ISSUE TITLE
The original outputs of DualRL

### ISSUE THREAD

**Issue by laihuiyuan** [luofuli/DualRL#23]
Hi Fuli,
Thanks for you great work.
I found that you released the lowercase output on Github. Since I would like to conduct some comparative experiments on the original results of different models, would you please share the original outputs of your model on the GYAFC (formality transfer dataset) with me?
Thank you very much for all your help!

**Comment by luofuli** [comment]
“original outputs” means uncased output？

**Comment by laihuiyuan** [comment]
Yes! The outputs of DualRL without any processing.  Would you please share them with me? Thank you!!!!

**Comment by luofuli** [comment]
Since the training data have been processed (cased), we only have the cased outputs. If you want the uncased outputs, you can re-train the model.
