### ISSUE TITLE
How to set the max_output_sequence_length

### ISSUE THREAD

**Issue by Karlguo** [luofuli/DualRL#5]
Hi, sorry to bother you again.
I print the shape of the output and find the maximum output seq length is 20 and lots of samples are pinched off from the middle because of this maximum seq length.
But I cannot find the position to set the maximum output seq length, where can I set it ?
Thank You!

Appendix: the shape of output I printed
![image](https://user-images.githubusercontent.com/11541136/60872881-1094da80-a268-11e9-9d57-d5bb2c2401a8.png)
(16 is the batch size, 10 is the decode_width. This is "random_prediction")

**Comment by luofuli** [comment]
There are two ways:
1. Set `maximum_iterations` in [nmt/options.py](https://github.com/luofuli/DualRL/blob/4ffa5ab85dd293b1534b1164182044bd044eb48b/nmt/options.py#L19). And I have updated it just now (Now:`default=100`, previous: `default=20`).
2. Add `--maximum_iterations` to the command. E.g, 
`python nmt.py --mode train --nmt_direction 0-1 --n_epoch 5 --maximum_iterations YOUR_MAX_LENGTH`

**Comment by Karlguo** [comment]
@luofuli Thank you, I got it
