### ISSUE TITLE
Question about the pseudo-parallel data in the DualRL training stage

### ISSUE THREAD

**Issue by sunny371** [luofuli/DualRL#9]
Thanks for your great work!

I have a question for the pseudo-parallel data used in the annealing pseudo teacher-forcing stage: From your paper, I notice the pseudo-parallel data is generated on-the-fly using the latest model. However, I find the codes for this in the [dual_training.py](https://github.com/luofuli/DualRL/blob/master/dual_training.py), as shown below,
https://github.com/luofuli/DualRL/blob/7983ec08900395ea1fe22861dd944b426b9c6064/dual_training.py#L84-L86
https://github.com/luofuli/DualRL/blob/7983ec08900395ea1fe22861dd944b426b9c6064/dual_training.py#L308-L317
just load paired data from **args.tsf_train_data** which stores the pseudo-parallel data generated by the template-based approach for pretraining, instead of generating with the latest model.

Did I understand this correctly? Have I missed anything?
Thank you.

**Comment by luofuli** [comment]
Uh oh! I made a mistake here when I cleaned the code. I have deleted the code which uses the pseudo-data generated on-the-fly but preserved the code which uses the original pseudo-parallel data. 

This figure shows the original code (before cleaning):
![image](https://user-images.githubusercontent.com/13479945/63222494-559f1b80-c1db-11e9-96e5-78d433342509.png)

Wait for a minute, I will update the code! Thanks!

**Comment by sunny371** [comment]
Thank you very much for your reply @luofuli .
But It seems there is still a problem. The **mid_ids_in_bs** is the transferred output from source style A to the target style B. Shouldn't this be used as the input_ids together with src[''ids''] as targets to train **nmts_train[B]** instead of **nmts_train[A]**, since the generated text should be put in the source side?

**Comment by luofuli** [comment]
Yes, you are right! I did not show you the whole code! The section of `previous_b` is right with you! I just do several ablation studies to validate which one can work! And I found out that `previous_b` works!

![image](https://user-images.githubusercontent.com/13479945/63222855-8e40f400-c1df-11e9-8a0d-a800691dd30d.png)

**Comment by sunny371** [comment]
Got it! Thanks a lot! @luofuli

**Comment by luofuli** [comment]
I have updated the code! If you don't have any questions, you can close the issue! Thanks for your feedback!
